/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdPlatform = IDL.Variant({
  'linkedin' : IDL.Null,
  'meta' : IDL.Null,
  'googleAds' : IDL.Null,
  'youtube' : IDL.Null,
});
export const AdCampaign = IDL.Record({
  'id' : IDL.Nat,
  'clicks' : IDL.Nat,
  'createdAt' : IDL.Int,
  'impressions' : IDL.Nat,
  'platform' : AdPlatform,
  'spend' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'conversions' : IDL.Nat,
  'budget' : IDL.Float64,
  'campaignName' : IDL.Text,
});
export const EmailCampaign = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'sent' : IDL.Null,
    'draft' : IDL.Null,
  }),
  'bodyContent' : IDL.Text,
  'subjectLine' : IDL.Text,
  'createdAt' : IDL.Int,
  'targetAudience' : IDL.Text,
  'updatedAt' : IDL.Int,
  'campaignName' : IDL.Text,
});
export const LandingPageStatus = IDL.Variant({
  'active' : IDL.Null,
  'draft' : IDL.Null,
  'paused' : IDL.Null,
});
export const LandingPage = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'status' : LandingPageStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'associatedCampaign' : IDL.Text,
  'updatedAt' : IDL.Int,
  'conversionGoal' : IDL.Text,
});
export const LeadStatus = IDL.Variant({
  'won' : IDL.Null,
  'lost' : IDL.Null,
  'in_progress' : IDL.Null,
  'open' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const SocialMediaPlatform = IDL.Variant({
  'linkedin' : IDL.Null,
  'tiktok' : IDL.Null,
  'twitter' : IDL.Null,
  'other' : IDL.Null,
  'instagram' : IDL.Null,
  'facebook' : IDL.Null,
  'youtube' : IDL.Null,
});
export const SocialMediaMetrics = IDL.Record({
  'id' : IDL.Nat,
  'clicks' : IDL.Nat,
  'engagements' : IDL.Nat,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'impressions' : IDL.Nat,
  'platform' : SocialMediaPlatform,
  'notes' : IDL.Text,
  'postsPublished' : IDL.Nat,
  'followers' : IDL.Nat,
  'reach' : IDL.Nat,
});
export const PostStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'idea' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const SocialMediaPost = IDL.Record({
  'id' : IDL.Nat,
  'status' : PostStatus,
  'title' : IDL.Text,
  'scheduledDate' : IDL.Opt(IDL.Int),
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'platform' : SocialMediaPlatform,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'caption' : IDL.Text,
});
export const SEOEntry = IDL.Record({
  'id' : IDL.Nat,
  'metaDescription' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'pageUrl' : IDL.Text,
  'targetKeywords' : IDL.Vec(IDL.Text),
  'metaTitle' : IDL.Text,
});
export const WebhookLog = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'timestamp' : IDL.Int,
  'toolName' : IDL.Text,
  'payload' : IDL.Text,
});
export const ExportPayload = IDL.Record({
  'metrics' : IDL.Vec(SocialMediaMetrics),
  'leads' : IDL.Vec(Lead),
  'posts' : IDL.Vec(SocialMediaPost),
  'webhookLogs' : IDL.Vec(WebhookLog),
});
export const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
export const PublicLeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed_won' : IDL.Null,
  'contacted' : IDL.Null,
  'proposal_sent' : IDL.Null,
  'qualified' : IDL.Null,
});
export const PublicLead = IDL.Record({
  'id' : IDL.Nat,
  'status' : PublicLeadStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const PublicPackage = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const PublicAddon = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
export const PublicService = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'packages' : IDL.Vec(PublicPackage),
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'addons' : IDL.Vec(PublicAddon),
  'isVisible' : IDL.Bool,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearExternalWebhookLogs' : IDL.Func([], [], []),
  'createAdCampaign' : IDL.Func(
      [
        IDL.Text,
        AdPlatform,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [AdCampaign],
      [],
    ),
  'createEmailCampaign' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'active' : IDL.Null,
          'sent' : IDL.Null,
          'draft' : IDL.Null,
        }),
      ],
      [EmailCampaign],
      [],
    ),
  'createLandingPage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, LandingPageStatus],
      [LandingPage],
      [],
    ),
  'createLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, LeadStatus, IDL.Text],
      [Lead],
      [],
    ),
  'createMetrics' : IDL.Func(
      [
        SocialMediaPlatform,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [SocialMediaMetrics],
      [],
    ),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        SocialMediaPlatform,
        PostStatus,
        IDL.Opt(IDL.Int),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [SocialMediaPost],
      [],
    ),
  'createSEOEntry' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [SEOEntry],
      [],
    ),
  'deleteAdCampaign' : IDL.Func([IDL.Nat], [], []),
  'deleteEmailCampaign' : IDL.Func([IDL.Nat], [], []),
  'deleteLandingPage' : IDL.Func([IDL.Nat], [], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteMetrics' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'deleteSEOEntry' : IDL.Func([IDL.Nat], [], []),
  'exportData' : IDL.Func([], [ExportPayload], ['query']),
  'getAdCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(AdCampaign)], ['query']),
  'getAllAdCampaigns' : IDL.Func([], [IDL.Vec(AdCampaign)], ['query']),
  'getAllEmailCampaigns' : IDL.Func([], [IDL.Vec(EmailCampaign)], ['query']),
  'getAllLandingPages' : IDL.Func([], [IDL.Vec(LandingPage)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllLeadsPagination' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Lead)],
      ['query'],
    ),
  'getAllMetrics' : IDL.Func([], [IDL.Vec(SocialMediaMetrics)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(SocialMediaPost)], ['query']),
  'getAllSEOEntries' : IDL.Func([], [IDL.Vec(SEOEntry)], ['query']),
  'getAllServicesWithVisibility' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmailCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(EmailCampaign)], ['query']),
  'getExternalWebhookLogs' : IDL.Func([], [IDL.Vec(WebhookLog)], ['query']),
  'getLandingPage' : IDL.Func([IDL.Nat], [IDL.Opt(LandingPage)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
  'getMetrics' : IDL.Func([IDL.Nat], [IDL.Opt(SocialMediaMetrics)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(SocialMediaPost)], ['query']),
  'getSEOEntry' : IDL.Func([IDL.Nat], [IDL.Opt(SEOEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importLeads' : IDL.Func([IDL.Vec(Lead)], [IDL.Vec(IDL.Nat)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isServiceVisible' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'publicCreateLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, PublicLeadStatus, IDL.Text],
      [PublicLead],
      [],
    ),
  'publicCreateService' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(PublicPackage),
        IDL.Vec(PublicAddon),
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
      ],
      [PublicService],
      [],
    ),
  'publicDeleteLead' : IDL.Func([IDL.Nat], [], []),
  'publicDeleteService' : IDL.Func([IDL.Text], [], []),
  'publicGetAllLeads' : IDL.Func([], [IDL.Vec(PublicLead)], ['query']),
  'publicGetAllServices' : IDL.Func([], [IDL.Vec(PublicService)], ['query']),
  'publicImportLeads' : IDL.Func(
      [
        IDL.Vec(
          IDL.Record({
            'status' : PublicLeadStatus,
            'name' : IDL.Text,
            'email' : IDL.Text,
            'notes' : IDL.Text,
            'phone' : IDL.Text,
          })
        ),
      ],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'publicSeedServices' : IDL.Func([IDL.Vec(PublicService)], [IDL.Nat], []),
  'publicSetServiceVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'publicUpdateLead' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, PublicLeadStatus, IDL.Text],
      [PublicLead],
      [],
    ),
  'publicUpdateService' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(PublicPackage),
        IDL.Vec(PublicAddon),
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
      ],
      [PublicService],
      [],
    ),
  'receiveExternalWebhook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setServiceVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateAdCampaign' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        AdPlatform,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [AdCampaign],
      [],
    ),
  'updateEmailCampaign' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'active' : IDL.Null,
          'sent' : IDL.Null,
          'draft' : IDL.Null,
        }),
      ],
      [EmailCampaign],
      [],
    ),
  'updateLandingPage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, LandingPageStatus],
      [LandingPage],
      [],
    ),
  'updateLead' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, LeadStatus, IDL.Text],
      [Lead],
      [],
    ),
  'updateMetrics' : IDL.Func(
      [
        IDL.Nat,
        SocialMediaPlatform,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [SocialMediaMetrics],
      [],
    ),
  'updatePost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        SocialMediaPlatform,
        PostStatus,
        IDL.Opt(IDL.Int),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [SocialMediaPost],
      [],
    ),
  'updateSEOEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [SEOEntry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdPlatform = IDL.Variant({
    'linkedin' : IDL.Null,
    'meta' : IDL.Null,
    'googleAds' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const AdCampaign = IDL.Record({
    'id' : IDL.Nat,
    'clicks' : IDL.Nat,
    'createdAt' : IDL.Int,
    'impressions' : IDL.Nat,
    'platform' : AdPlatform,
    'spend' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'conversions' : IDL.Nat,
    'budget' : IDL.Float64,
    'campaignName' : IDL.Text,
  });
  const EmailCampaign = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'sent' : IDL.Null,
      'draft' : IDL.Null,
    }),
    'bodyContent' : IDL.Text,
    'subjectLine' : IDL.Text,
    'createdAt' : IDL.Int,
    'targetAudience' : IDL.Text,
    'updatedAt' : IDL.Int,
    'campaignName' : IDL.Text,
  });
  const LandingPageStatus = IDL.Variant({
    'active' : IDL.Null,
    'draft' : IDL.Null,
    'paused' : IDL.Null,
  });
  const LandingPage = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'status' : LandingPageStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'associatedCampaign' : IDL.Text,
    'updatedAt' : IDL.Int,
    'conversionGoal' : IDL.Text,
  });
  const LeadStatus = IDL.Variant({
    'won' : IDL.Null,
    'lost' : IDL.Null,
    'in_progress' : IDL.Null,
    'open' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SocialMediaPlatform = IDL.Variant({
    'linkedin' : IDL.Null,
    'tiktok' : IDL.Null,
    'twitter' : IDL.Null,
    'other' : IDL.Null,
    'instagram' : IDL.Null,
    'facebook' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const SocialMediaMetrics = IDL.Record({
    'id' : IDL.Nat,
    'clicks' : IDL.Nat,
    'engagements' : IDL.Nat,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'impressions' : IDL.Nat,
    'platform' : SocialMediaPlatform,
    'notes' : IDL.Text,
    'postsPublished' : IDL.Nat,
    'followers' : IDL.Nat,
    'reach' : IDL.Nat,
  });
  const PostStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'idea' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const SocialMediaPost = IDL.Record({
    'id' : IDL.Nat,
    'status' : PostStatus,
    'title' : IDL.Text,
    'scheduledDate' : IDL.Opt(IDL.Int),
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'platform' : SocialMediaPlatform,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'caption' : IDL.Text,
  });
  const SEOEntry = IDL.Record({
    'id' : IDL.Nat,
    'metaDescription' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'pageUrl' : IDL.Text,
    'targetKeywords' : IDL.Vec(IDL.Text),
    'metaTitle' : IDL.Text,
  });
  const WebhookLog = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'timestamp' : IDL.Int,
    'toolName' : IDL.Text,
    'payload' : IDL.Text,
  });
  const ExportPayload = IDL.Record({
    'metrics' : IDL.Vec(SocialMediaMetrics),
    'leads' : IDL.Vec(Lead),
    'posts' : IDL.Vec(SocialMediaPost),
    'webhookLogs' : IDL.Vec(WebhookLog),
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
  const PublicLeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed_won' : IDL.Null,
    'contacted' : IDL.Null,
    'proposal_sent' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const PublicLead = IDL.Record({
    'id' : IDL.Nat,
    'status' : PublicLeadStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PublicPackage = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PublicAddon = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
  const PublicService = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'packages' : IDL.Vec(PublicPackage),
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'addons' : IDL.Vec(PublicAddon),
    'isVisible' : IDL.Bool,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearExternalWebhookLogs' : IDL.Func([], [], []),
    'createAdCampaign' : IDL.Func(
        [
          IDL.Text,
          AdPlatform,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [AdCampaign],
        [],
      ),
    'createEmailCampaign' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'active' : IDL.Null,
            'sent' : IDL.Null,
            'draft' : IDL.Null,
          }),
        ],
        [EmailCampaign],
        [],
      ),
    'createLandingPage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, LandingPageStatus],
        [LandingPage],
        [],
      ),
    'createLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, LeadStatus, IDL.Text],
        [Lead],
        [],
      ),
    'createMetrics' : IDL.Func(
        [
          SocialMediaPlatform,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [SocialMediaMetrics],
        [],
      ),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          SocialMediaPlatform,
          PostStatus,
          IDL.Opt(IDL.Int),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [SocialMediaPost],
        [],
      ),
    'createSEOEntry' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [SEOEntry],
        [],
      ),
    'deleteAdCampaign' : IDL.Func([IDL.Nat], [], []),
    'deleteEmailCampaign' : IDL.Func([IDL.Nat], [], []),
    'deleteLandingPage' : IDL.Func([IDL.Nat], [], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteMetrics' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'deleteSEOEntry' : IDL.Func([IDL.Nat], [], []),
    'exportData' : IDL.Func([], [ExportPayload], ['query']),
    'getAdCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(AdCampaign)], ['query']),
    'getAllAdCampaigns' : IDL.Func([], [IDL.Vec(AdCampaign)], ['query']),
    'getAllEmailCampaigns' : IDL.Func([], [IDL.Vec(EmailCampaign)], ['query']),
    'getAllLandingPages' : IDL.Func([], [IDL.Vec(LandingPage)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllLeadsPagination' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Lead)],
        ['query'],
      ),
    'getAllMetrics' : IDL.Func([], [IDL.Vec(SocialMediaMetrics)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(SocialMediaPost)], ['query']),
    'getAllSEOEntries' : IDL.Func([], [IDL.Vec(SEOEntry)], ['query']),
    'getAllServicesWithVisibility' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmailCampaign' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(EmailCampaign)],
        ['query'],
      ),
    'getExternalWebhookLogs' : IDL.Func([], [IDL.Vec(WebhookLog)], ['query']),
    'getLandingPage' : IDL.Func([IDL.Nat], [IDL.Opt(LandingPage)], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
    'getMetrics' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SocialMediaMetrics)],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(SocialMediaPost)], ['query']),
    'getSEOEntry' : IDL.Func([IDL.Nat], [IDL.Opt(SEOEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importLeads' : IDL.Func([IDL.Vec(Lead)], [IDL.Vec(IDL.Nat)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isServiceVisible' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'publicCreateLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, PublicLeadStatus, IDL.Text],
        [PublicLead],
        [],
      ),
    'publicCreateService' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(PublicPackage),
          IDL.Vec(PublicAddon),
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
        ],
        [PublicService],
        [],
      ),
    'publicDeleteLead' : IDL.Func([IDL.Nat], [], []),
    'publicDeleteService' : IDL.Func([IDL.Text], [], []),
    'publicGetAllLeads' : IDL.Func([], [IDL.Vec(PublicLead)], ['query']),
    'publicGetAllServices' : IDL.Func([], [IDL.Vec(PublicService)], ['query']),
    'publicImportLeads' : IDL.Func(
        [
          IDL.Vec(
            IDL.Record({
              'status' : PublicLeadStatus,
              'name' : IDL.Text,
              'email' : IDL.Text,
              'notes' : IDL.Text,
              'phone' : IDL.Text,
            })
          ),
        ],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'publicSeedServices' : IDL.Func([IDL.Vec(PublicService)], [IDL.Nat], []),
    'publicSetServiceVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'publicUpdateLead' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, PublicLeadStatus, IDL.Text],
        [PublicLead],
        [],
      ),
    'publicUpdateService' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(PublicPackage),
          IDL.Vec(PublicAddon),
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
        ],
        [PublicService],
        [],
      ),
    'receiveExternalWebhook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setServiceVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateAdCampaign' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          AdPlatform,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [AdCampaign],
        [],
      ),
    'updateEmailCampaign' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'active' : IDL.Null,
            'sent' : IDL.Null,
            'draft' : IDL.Null,
          }),
        ],
        [EmailCampaign],
        [],
      ),
    'updateLandingPage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, LandingPageStatus],
        [LandingPage],
        [],
      ),
    'updateLead' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, LeadStatus, IDL.Text],
        [Lead],
        [],
      ),
    'updateMetrics' : IDL.Func(
        [
          IDL.Nat,
          SocialMediaPlatform,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [SocialMediaMetrics],
        [],
      ),
    'updatePost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          SocialMediaPlatform,
          PostStatus,
          IDL.Opt(IDL.Int),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [SocialMediaPost],
        [],
      ),
    'updateSEOEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [SEOEntry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };