/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Package = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'tier' : IDL.Text,
  'priceINR' : IDL.Nat,
});
export const Addon = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'packages' : IDL.Vec(Package),
  'sortOrder' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'maintenancePlan' : IDL.Nat,
  'addons' : IDL.Vec(Addon),
  'isVisible' : IDL.Bool,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Lead],
      [],
    ),
  'createService' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Package),
        IDL.Vec(Addon),
        IDL.Nat,
        IDL.Bool,
        IDL.Int,
      ],
      [Service],
      [],
    ),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'duplicateService' : IDL.Func([IDL.Nat], [Service], []),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'reorderServices' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'updateLead' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Lead],
      [],
    ),
  'updateService' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Package),
        IDL.Vec(Addon),
        IDL.Nat,
        IDL.Bool,
        IDL.Int,
      ],
      [Service],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Package = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'tier' : IDL.Text,
    'priceINR' : IDL.Nat,
  });
  const Addon = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'packages' : IDL.Vec(Package),
    'sortOrder' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'maintenancePlan' : IDL.Nat,
    'addons' : IDL.Vec(Addon),
    'isVisible' : IDL.Bool,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Lead],
        [],
      ),
    'createService' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Package),
          IDL.Vec(Addon),
          IDL.Nat,
          IDL.Bool,
          IDL.Int,
        ],
        [Service],
        [],
      ),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'duplicateService' : IDL.Func([IDL.Nat], [Service], []),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'reorderServices' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'updateLead' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Lead],
        [],
      ),
    'updateService' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Package),
          IDL.Vec(Addon),
          IDL.Nat,
          IDL.Bool,
          IDL.Int,
        ],
        [Service],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };