/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SocialMediaPlatform = IDL.Variant({
  'linkedin' : IDL.Null,
  'tiktok' : IDL.Null,
  'twitter' : IDL.Null,
  'other' : IDL.Null,
  'instagram' : IDL.Null,
  'facebook' : IDL.Null,
  'youtube' : IDL.Null,
});
export const SocialMediaMetrics = IDL.Record({
  'id' : IDL.Nat,
  'clicks' : IDL.Nat,
  'engagements' : IDL.Nat,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'impressions' : IDL.Nat,
  'platform' : SocialMediaPlatform,
  'notes' : IDL.Text,
  'postsPublished' : IDL.Nat,
  'followers' : IDL.Nat,
  'reach' : IDL.Nat,
});
export const PostStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'idea' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const SocialMediaPost = IDL.Record({
  'id' : IDL.Nat,
  'status' : PostStatus,
  'title' : IDL.Text,
  'scheduledDate' : IDL.Opt(IDL.Int),
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'platform' : SocialMediaPlatform,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'caption' : IDL.Text,
});
export const WebhookLog = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'timestamp' : IDL.Int,
  'toolName' : IDL.Text,
  'payload' : IDL.Text,
});
export const ExportPayload = IDL.Record({
  'metrics' : IDL.Vec(SocialMediaMetrics),
  'posts' : IDL.Vec(SocialMediaPost),
  'webhookLogs' : IDL.Vec(WebhookLog),
});
export const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearExternalWebhookLogs' : IDL.Func([], [], []),
  'createMetrics' : IDL.Func(
      [
        SocialMediaPlatform,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [SocialMediaMetrics],
      [],
    ),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        SocialMediaPlatform,
        PostStatus,
        IDL.Opt(IDL.Int),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [SocialMediaPost],
      [],
    ),
  'deleteMetrics' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'exportData' : IDL.Func([], [ExportPayload], ['query']),
  'getAllMetrics' : IDL.Func([], [IDL.Vec(SocialMediaMetrics)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(SocialMediaPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExternalWebhookLogs' : IDL.Func([], [IDL.Vec(WebhookLog)], ['query']),
  'getMetrics' : IDL.Func([IDL.Nat], [IDL.Opt(SocialMediaMetrics)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(SocialMediaPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'receiveExternalWebhook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMetrics' : IDL.Func(
      [
        IDL.Nat,
        SocialMediaPlatform,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [SocialMediaMetrics],
      [],
    ),
  'updatePost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        SocialMediaPlatform,
        PostStatus,
        IDL.Opt(IDL.Int),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [SocialMediaPost],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SocialMediaPlatform = IDL.Variant({
    'linkedin' : IDL.Null,
    'tiktok' : IDL.Null,
    'twitter' : IDL.Null,
    'other' : IDL.Null,
    'instagram' : IDL.Null,
    'facebook' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const SocialMediaMetrics = IDL.Record({
    'id' : IDL.Nat,
    'clicks' : IDL.Nat,
    'engagements' : IDL.Nat,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'impressions' : IDL.Nat,
    'platform' : SocialMediaPlatform,
    'notes' : IDL.Text,
    'postsPublished' : IDL.Nat,
    'followers' : IDL.Nat,
    'reach' : IDL.Nat,
  });
  const PostStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'idea' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const SocialMediaPost = IDL.Record({
    'id' : IDL.Nat,
    'status' : PostStatus,
    'title' : IDL.Text,
    'scheduledDate' : IDL.Opt(IDL.Int),
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'platform' : SocialMediaPlatform,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'caption' : IDL.Text,
  });
  const WebhookLog = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'timestamp' : IDL.Int,
    'toolName' : IDL.Text,
    'payload' : IDL.Text,
  });
  const ExportPayload = IDL.Record({
    'metrics' : IDL.Vec(SocialMediaMetrics),
    'posts' : IDL.Vec(SocialMediaPost),
    'webhookLogs' : IDL.Vec(WebhookLog),
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearExternalWebhookLogs' : IDL.Func([], [], []),
    'createMetrics' : IDL.Func(
        [
          SocialMediaPlatform,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [SocialMediaMetrics],
        [],
      ),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          SocialMediaPlatform,
          PostStatus,
          IDL.Opt(IDL.Int),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [SocialMediaPost],
        [],
      ),
    'deleteMetrics' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'exportData' : IDL.Func([], [ExportPayload], ['query']),
    'getAllMetrics' : IDL.Func([], [IDL.Vec(SocialMediaMetrics)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(SocialMediaPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExternalWebhookLogs' : IDL.Func([], [IDL.Vec(WebhookLog)], ['query']),
    'getMetrics' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SocialMediaMetrics)],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(SocialMediaPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'receiveExternalWebhook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMetrics' : IDL.Func(
        [
          IDL.Nat,
          SocialMediaPlatform,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [SocialMediaMetrics],
        [],
      ),
    'updatePost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          SocialMediaPlatform,
          PostStatus,
          IDL.Opt(IDL.Int),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [SocialMediaPost],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };