/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Addon { 'name' : string, 'price' : bigint }
export interface Lead {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'email' : string,
  'serviceInterest' : string,
  'notes' : string,
  'phone' : string,
}
export interface Package {
  'features' : Array<string>,
  'tier' : string,
  'priceINR' : bigint,
}
export interface Service {
  'id' : bigint,
  'packages' : Array<Package>,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'maintenancePlan' : bigint,
  'addons' : Array<Addon>,
  'isVisible' : boolean,
  'category' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createLead' : ActorMethod<
    [string, string, string, string, string, string],
    Lead
  >,
  'createService' : ActorMethod<
    [
      string,
      string,
      string,
      Array<Package>,
      Array<Addon>,
      bigint,
      boolean,
      bigint,
    ],
    Service
  >,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'duplicateService' : ActorMethod<[bigint], Service>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'reorderServices' : ActorMethod<[Array<bigint>], undefined>,
  'updateLead' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    Lead
  >,
  'updateService' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Array<Package>,
      Array<Addon>,
      bigint,
      boolean,
      bigint,
    ],
    Service
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];