/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdCampaign {
  'id' : bigint,
  'clicks' : bigint,
  'createdAt' : bigint,
  'impressions' : bigint,
  'platform' : AdPlatform,
  'spend' : number,
  'updatedAt' : bigint,
  'conversions' : bigint,
  'budget' : number,
  'campaignName' : string,
}
export type AdPlatform = { 'linkedin' : null } |
  { 'meta' : null } |
  { 'googleAds' : null } |
  { 'youtube' : null };
export interface EmailCampaign {
  'id' : bigint,
  'status' : { 'active' : null } |
    { 'sent' : null } |
    { 'draft' : null },
  'bodyContent' : string,
  'subjectLine' : string,
  'createdAt' : bigint,
  'targetAudience' : string,
  'updatedAt' : bigint,
  'campaignName' : string,
}
export interface ExportPayload {
  'metrics' : Array<SocialMediaMetrics>,
  'posts' : Array<SocialMediaPost>,
  'webhookLogs' : Array<WebhookLog>,
}
export interface LandingPage {
  'id' : bigint,
  'url' : string,
  'status' : LandingPageStatus,
  'name' : string,
  'createdAt' : bigint,
  'associatedCampaign' : string,
  'updatedAt' : bigint,
  'conversionGoal' : string,
}
export type LandingPageStatus = { 'active' : null } |
  { 'draft' : null } |
  { 'paused' : null };
export type PostStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'idea' : null } |
  { 'published' : null } |
  { 'draft' : null };
export interface SEOEntry {
  'id' : bigint,
  'metaDescription' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'pageUrl' : string,
  'targetKeywords' : Array<string>,
  'metaTitle' : string,
}
export interface SocialMediaMetrics {
  'id' : bigint,
  'clicks' : bigint,
  'engagements' : bigint,
  'date' : bigint,
  'createdAt' : bigint,
  'impressions' : bigint,
  'platform' : SocialMediaPlatform,
  'notes' : string,
  'postsPublished' : bigint,
  'followers' : bigint,
  'reach' : bigint,
}
export type SocialMediaPlatform = { 'linkedin' : null } |
  { 'tiktok' : null } |
  { 'twitter' : null } |
  { 'other' : null } |
  { 'instagram' : null } |
  { 'facebook' : null } |
  { 'youtube' : null };
export interface SocialMediaPost {
  'id' : bigint,
  'status' : PostStatus,
  'title' : string,
  'scheduledDate' : [] | [bigint],
  'createdAt' : bigint,
  'tags' : Array<string>,
  'platform' : SocialMediaPlatform,
  'updatedAt' : bigint,
  'notes' : string,
  'caption' : string,
}
export interface UserProfile { 'bio' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebhookLog {
  'id' : bigint,
  'source' : string,
  'timestamp' : bigint,
  'toolName' : string,
  'payload' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearExternalWebhookLogs' : ActorMethod<[], undefined>,
  'createAdCampaign' : ActorMethod<
    [string, AdPlatform, number, number, bigint, bigint, bigint],
    AdCampaign
  >,
  'createEmailCampaign' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      { 'active' : null } |
        { 'sent' : null } |
        { 'draft' : null },
    ],
    EmailCampaign
  >,
  'createLandingPage' : ActorMethod<
    [string, string, string, string, LandingPageStatus],
    LandingPage
  >,
  'createMetrics' : ActorMethod<
    [
      SocialMediaPlatform,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
    ],
    SocialMediaMetrics
  >,
  'createPost' : ActorMethod<
    [
      string,
      string,
      SocialMediaPlatform,
      PostStatus,
      [] | [bigint],
      Array<string>,
      string,
    ],
    SocialMediaPost
  >,
  'createSEOEntry' : ActorMethod<
    [string, Array<string>, string, string],
    SEOEntry
  >,
  'deleteAdCampaign' : ActorMethod<[bigint], undefined>,
  'deleteEmailCampaign' : ActorMethod<[bigint], undefined>,
  'deleteLandingPage' : ActorMethod<[bigint], undefined>,
  'deleteMetrics' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'deleteSEOEntry' : ActorMethod<[bigint], undefined>,
  'exportData' : ActorMethod<[], ExportPayload>,
  'getAdCampaign' : ActorMethod<[bigint], [] | [AdCampaign]>,
  'getAllAdCampaigns' : ActorMethod<[], Array<AdCampaign>>,
  'getAllEmailCampaigns' : ActorMethod<[], Array<EmailCampaign>>,
  'getAllLandingPages' : ActorMethod<[], Array<LandingPage>>,
  'getAllMetrics' : ActorMethod<[], Array<SocialMediaMetrics>>,
  'getAllPosts' : ActorMethod<[], Array<SocialMediaPost>>,
  'getAllSEOEntries' : ActorMethod<[], Array<SEOEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmailCampaign' : ActorMethod<[bigint], [] | [EmailCampaign]>,
  'getExternalWebhookLogs' : ActorMethod<[], Array<WebhookLog>>,
  'getLandingPage' : ActorMethod<[bigint], [] | [LandingPage]>,
  'getMetrics' : ActorMethod<[bigint], [] | [SocialMediaMetrics]>,
  'getPost' : ActorMethod<[bigint], [] | [SocialMediaPost]>,
  'getSEOEntry' : ActorMethod<[bigint], [] | [SEOEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'receiveExternalWebhook' : ActorMethod<[string, string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAdCampaign' : ActorMethod<
    [bigint, string, AdPlatform, number, number, bigint, bigint, bigint],
    AdCampaign
  >,
  'updateEmailCampaign' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      { 'active' : null } |
        { 'sent' : null } |
        { 'draft' : null },
    ],
    EmailCampaign
  >,
  'updateLandingPage' : ActorMethod<
    [bigint, string, string, string, string, LandingPageStatus],
    LandingPage
  >,
  'updateMetrics' : ActorMethod<
    [
      bigint,
      SocialMediaPlatform,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
    ],
    SocialMediaMetrics
  >,
  'updatePost' : ActorMethod<
    [
      bigint,
      string,
      string,
      SocialMediaPlatform,
      PostStatus,
      [] | [bigint],
      Array<string>,
      string,
    ],
    SocialMediaPost
  >,
  'updateSEOEntry' : ActorMethod<
    [bigint, string, Array<string>, string, string],
    SEOEntry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];