/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WebhookLog {
    id: bigint;
    source: string;
    timestamp: bigint;
    toolName: string;
    payload: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PublicLead {
    id: bigint;
    status: PublicLeadStatus;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
}
export interface SEOEntry {
    id: bigint;
    metaDescription: string;
    createdAt: bigint;
    updatedAt: bigint;
    pageUrl: string;
    targetKeywords: Array<string>;
    metaTitle: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ExportPayload {
    metrics: Array<SocialMediaMetrics>;
    leads: Array<Lead>;
    posts: Array<SocialMediaPost>;
    webhookLogs: Array<WebhookLog>;
}
export interface PublicPackage {
    features: Array<string>;
    name: string;
    price: bigint;
}
export interface SocialMediaMetrics {
    id: bigint;
    clicks: bigint;
    engagements: bigint;
    date: bigint;
    createdAt: bigint;
    impressions: bigint;
    platform: SocialMediaPlatform;
    notes: string;
    postsPublished: bigint;
    followers: bigint;
    reach: bigint;
}
export interface PublicService {
    id: string;
    title: string;
    packages: Array<PublicPackage>;
    sortOrder: bigint;
    description: string;
    imageUrl: string;
    addons: Array<PublicAddon>;
    isVisible: boolean;
    category: string;
}
export interface Lead {
    id: bigint;
    status: LeadStatus;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
}
export interface AdCampaign {
    id: bigint;
    clicks: bigint;
    createdAt: bigint;
    impressions: bigint;
    platform: AdPlatform;
    spend: number;
    updatedAt: bigint;
    conversions: bigint;
    budget: number;
    campaignName: string;
}
export interface SocialMediaPost {
    id: bigint;
    status: PostStatus;
    title: string;
    scheduledDate?: bigint;
    createdAt: bigint;
    tags: Array<string>;
    platform: SocialMediaPlatform;
    updatedAt: bigint;
    notes: string;
    caption: string;
}
export interface PublicAddon {
    name: string;
    price: bigint;
}
export interface LandingPage {
    id: bigint;
    url: string;
    status: LandingPageStatus;
    name: string;
    createdAt: bigint;
    associatedCampaign: string;
    updatedAt: bigint;
    conversionGoal: string;
}
export interface EmailCampaign {
    id: bigint;
    status: Variant_active_sent_draft;
    bodyContent: string;
    subjectLine: string;
    createdAt: bigint;
    targetAudience: string;
    updatedAt: bigint;
    campaignName: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    bio: string;
    name: string;
}
export enum AdPlatform {
    linkedin = "linkedin",
    meta = "meta",
    googleAds = "googleAds",
    youtube = "youtube"
}
export enum LandingPageStatus {
    active = "active",
    draft = "draft",
    paused = "paused"
}
export enum LeadStatus {
    won = "won",
    lost = "lost",
    in_progress = "in_progress",
    open = "open"
}
export enum PostStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    idea = "idea",
    published = "published",
    draft = "draft"
}
export enum PublicLeadStatus {
    new_ = "new",
    closed_won = "closed_won",
    contacted = "contacted",
    proposal_sent = "proposal_sent",
    qualified = "qualified"
}
export enum SocialMediaPlatform {
    linkedin = "linkedin",
    tiktok = "tiktok",
    twitter = "twitter",
    other = "other",
    instagram = "instagram",
    facebook = "facebook",
    youtube = "youtube"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_sent_draft {
    active = "active",
    sent = "sent",
    draft = "draft"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearExternalWebhookLogs(): Promise<void>;
    createAdCampaign(campaignName: string, platform: AdPlatform, budget: number, spend: number, impressions: bigint, clicks: bigint, conversions: bigint): Promise<AdCampaign>;
    createEmailCampaign(campaignName: string, subjectLine: string, bodyContent: string, targetAudience: string, status: Variant_active_sent_draft): Promise<EmailCampaign>;
    createLandingPage(name: string, url: string, associatedCampaign: string, conversionGoal: string, status: LandingPageStatus): Promise<LandingPage>;
    createLead(name: string, email: string, phone: string, status: LeadStatus, notes: string): Promise<Lead>;
    createMetrics(platform: SocialMediaPlatform, date: bigint, followers: bigint, impressions: bigint, reach: bigint, engagements: bigint, clicks: bigint, postsPublished: bigint, notes: string): Promise<SocialMediaMetrics>;
    createPost(title: string, caption: string, platform: SocialMediaPlatform, status: PostStatus, scheduledDate: bigint | null, tags: Array<string>, notes: string): Promise<SocialMediaPost>;
    createSEOEntry(pageUrl: string, targetKeywords: Array<string>, metaTitle: string, metaDescription: string): Promise<SEOEntry>;
    deleteAdCampaign(id: bigint): Promise<void>;
    deleteEmailCampaign(id: bigint): Promise<void>;
    deleteLandingPage(id: bigint): Promise<void>;
    deleteLead(id: bigint): Promise<void>;
    deleteMetrics(id: bigint): Promise<void>;
    deletePost(id: bigint): Promise<void>;
    deleteSEOEntry(id: bigint): Promise<void>;
    exportData(): Promise<ExportPayload>;
    getAdCampaign(id: bigint): Promise<AdCampaign | null>;
    getAllAdCampaigns(): Promise<Array<AdCampaign>>;
    getAllEmailCampaigns(): Promise<Array<EmailCampaign>>;
    getAllLandingPages(): Promise<Array<LandingPage>>;
    getAllLeads(): Promise<Array<Lead>>;
    getAllLeadsPagination(page: bigint, pageSize: bigint): Promise<Array<Lead>>;
    getAllMetrics(): Promise<Array<SocialMediaMetrics>>;
    getAllPosts(): Promise<Array<SocialMediaPost>>;
    getAllSEOEntries(): Promise<Array<SEOEntry>>;
    getAllServicesWithVisibility(): Promise<Array<[string, boolean]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmailCampaign(id: bigint): Promise<EmailCampaign | null>;
    getExternalWebhookLogs(): Promise<Array<WebhookLog>>;
    getLandingPage(id: bigint): Promise<LandingPage | null>;
    getLead(id: bigint): Promise<Lead | null>;
    getMetrics(id: bigint): Promise<SocialMediaMetrics | null>;
    getPost(id: bigint): Promise<SocialMediaPost | null>;
    getSEOEntry(id: bigint): Promise<SEOEntry | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importLeads(importedLeads: Array<Lead>): Promise<Array<bigint>>;
    isCallerAdmin(): Promise<boolean>;
    isServiceVisible(serviceName: string): Promise<boolean>;
    publicCreateLead(name: string, email: string, phone: string, status: PublicLeadStatus, notes: string): Promise<PublicLead>;
    publicCreateService(id: string, title: string, category: string, description: string, packages: Array<PublicPackage>, addons: Array<PublicAddon>, imageUrl: string, isVisible: boolean, sortOrder: bigint): Promise<PublicService>;
    publicDeleteLead(id: bigint): Promise<void>;
    publicDeleteService(id: string): Promise<void>;
    publicGetAllLeads(): Promise<Array<PublicLead>>;
    publicGetAllServices(): Promise<Array<PublicService>>;
    publicImportLeads(items: Array<{
        status: PublicLeadStatus;
        name: string;
        email: string;
        notes: string;
        phone: string;
    }>): Promise<Array<bigint>>;
    publicSeedServices(items: Array<PublicService>): Promise<bigint>;
    publicSetServiceVisibility(id: string, isVisible: boolean): Promise<void>;
    publicUpdateLead(id: bigint, name: string, email: string, phone: string, status: PublicLeadStatus, notes: string): Promise<PublicLead>;
    publicUpdateService(id: string, title: string, category: string, description: string, packages: Array<PublicPackage>, addons: Array<PublicAddon>, imageUrl: string, isVisible: boolean, sortOrder: bigint): Promise<PublicService>;
    receiveExternalWebhook(toolName: string, payload: string, source: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setServiceVisibility(serviceName: string, isVisible: boolean): Promise<void>;
    updateAdCampaign(id: bigint, campaignName: string, platform: AdPlatform, budget: number, spend: number, impressions: bigint, clicks: bigint, conversions: bigint): Promise<AdCampaign>;
    updateEmailCampaign(id: bigint, campaignName: string, subjectLine: string, bodyContent: string, targetAudience: string, status: Variant_active_sent_draft): Promise<EmailCampaign>;
    updateLandingPage(id: bigint, name: string, url: string, associatedCampaign: string, conversionGoal: string, status: LandingPageStatus): Promise<LandingPage>;
    updateLead(id: bigint, name: string, email: string, phone: string, status: LeadStatus, notes: string): Promise<Lead>;
    updateMetrics(id: bigint, platform: SocialMediaPlatform, date: bigint, followers: bigint, impressions: bigint, reach: bigint, engagements: bigint, clicks: bigint, postsPublished: bigint, notes: string): Promise<SocialMediaMetrics>;
    updatePost(id: bigint, title: string, caption: string, platform: SocialMediaPlatform, status: PostStatus, scheduledDate: bigint | null, tags: Array<string>, notes: string): Promise<SocialMediaPost>;
    updateSEOEntry(id: bigint, pageUrl: string, targetKeywords: Array<string>, metaTitle: string, metaDescription: string): Promise<SEOEntry>;
}
import type { AdCampaign as _AdCampaign, AdPlatform as _AdPlatform, EmailCampaign as _EmailCampaign, ExportPayload as _ExportPayload, LandingPage as _LandingPage, LandingPageStatus as _LandingPageStatus, Lead as _Lead, LeadStatus as _LeadStatus, PostStatus as _PostStatus, PublicLead as _PublicLead, PublicLeadStatus as _PublicLeadStatus, SEOEntry as _SEOEntry, SocialMediaMetrics as _SocialMediaMetrics, SocialMediaPlatform as _SocialMediaPlatform, SocialMediaPost as _SocialMediaPost, UserProfile as _UserProfile, UserRole as _UserRole, WebhookLog as _WebhookLog, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearExternalWebhookLogs(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearExternalWebhookLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearExternalWebhookLogs();
            return result;
        }
    }
    async createAdCampaign(arg0: string, arg1: AdPlatform, arg2: number, arg3: number, arg4: bigint, arg5: bigint, arg6: bigint): Promise<AdCampaign> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdCampaign(arg0, to_candid_AdPlatform_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return from_candid_AdCampaign_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdCampaign(arg0, to_candid_AdPlatform_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return from_candid_AdCampaign_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEmailCampaign(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Variant_active_sent_draft): Promise<EmailCampaign> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmailCampaign(arg0, arg1, arg2, arg3, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg4));
                return from_candid_EmailCampaign_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmailCampaign(arg0, arg1, arg2, arg3, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg4));
            return from_candid_EmailCampaign_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLandingPage(arg0: string, arg1: string, arg2: string, arg3: string, arg4: LandingPageStatus): Promise<LandingPage> {
        if (this.processError) {
            try {
                const result = await this.actor.createLandingPage(arg0, arg1, arg2, arg3, to_candid_LandingPageStatus_n20(this._uploadFile, this._downloadFile, arg4));
                return from_candid_LandingPage_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLandingPage(arg0, arg1, arg2, arg3, to_candid_LandingPageStatus_n20(this._uploadFile, this._downloadFile, arg4));
            return from_candid_LandingPage_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLead(arg0: string, arg1: string, arg2: string, arg3: LeadStatus, arg4: string): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0, arg1, arg2, to_candid_LeadStatus_n26(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Lead_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0, arg1, arg2, to_candid_LeadStatus_n26(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Lead_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMetrics(arg0: SocialMediaPlatform, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: string): Promise<SocialMediaMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.createMetrics(to_candid_SocialMediaPlatform_n32(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_SocialMediaMetrics_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMetrics(to_candid_SocialMediaPlatform_n32(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_SocialMediaMetrics_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPost(arg0: string, arg1: string, arg2: SocialMediaPlatform, arg3: PostStatus, arg4: bigint | null, arg5: Array<string>, arg6: string): Promise<SocialMediaPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, to_candid_SocialMediaPlatform_n32(this._uploadFile, this._downloadFile, arg2), to_candid_PostStatus_n38(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return from_candid_SocialMediaPost_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, to_candid_SocialMediaPlatform_n32(this._uploadFile, this._downloadFile, arg2), to_candid_PostStatus_n38(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return from_candid_SocialMediaPost_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSEOEntry(arg0: string, arg1: Array<string>, arg2: string, arg3: string): Promise<SEOEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createSEOEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSEOEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteAdCampaign(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdCampaign(arg0);
            return result;
        }
    }
    async deleteEmailCampaign(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmailCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmailCampaign(arg0);
            return result;
        }
    }
    async deleteLandingPage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLandingPage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLandingPage(arg0);
            return result;
        }
    }
    async deleteLead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteMetrics(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMetrics(arg0);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteSEOEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSEOEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSEOEntry(arg0);
            return result;
        }
    }
    async exportData(): Promise<ExportPayload> {
        if (this.processError) {
            try {
                const result = await this.actor.exportData();
                return from_candid_ExportPayload_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportData();
            return from_candid_ExportPayload_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdCampaign(arg0: bigint): Promise<AdCampaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdCampaign(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdCampaign(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAdCampaigns(): Promise<Array<AdCampaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdCampaigns();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdCampaigns();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmailCampaigns(): Promise<Array<EmailCampaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmailCampaigns();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmailCampaigns();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLandingPages(): Promise<Array<LandingPage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLandingPages();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLandingPages();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLeadsPagination(arg0: bigint, arg1: bigint): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeadsPagination(arg0, arg1);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeadsPagination(arg0, arg1);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMetrics(): Promise<Array<SocialMediaMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMetrics();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMetrics();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPosts(): Promise<Array<SocialMediaPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSEOEntries(): Promise<Array<SEOEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSEOEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSEOEntries();
            return result;
        }
    }
    async getAllServicesWithVisibility(): Promise<Array<[string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServicesWithVisibility();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServicesWithVisibility();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmailCampaign(arg0: bigint): Promise<EmailCampaign | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailCampaign(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailCampaign(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExternalWebhookLogs(): Promise<Array<WebhookLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExternalWebhookLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExternalWebhookLogs();
            return result;
        }
    }
    async getLandingPage(arg0: bigint): Promise<LandingPage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandingPage(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandingPage(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: bigint): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetrics(arg0: bigint): Promise<SocialMediaMetrics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: bigint): Promise<SocialMediaPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSEOEntry(arg0: bigint): Promise<SEOEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSEOEntry(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSEOEntry(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async importLeads(arg0: Array<Lead>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.importLeads(to_candid_vec_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importLeads(to_candid_vec_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isServiceVisible(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isServiceVisible(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isServiceVisible(arg0);
            return result;
        }
    }
    async publicCreateLead(arg0: string, arg1: string, arg2: string, arg3: PublicLeadStatus, arg4: string): Promise<PublicLead> {
        if (this.processError) {
            try {
                const result = await this.actor.publicCreateLead(arg0, arg1, arg2, to_candid_PublicLeadStatus_n67(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_PublicLead_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicCreateLead(arg0, arg1, arg2, to_candid_PublicLeadStatus_n67(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_PublicLead_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async publicCreateService(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<PublicPackage>, arg5: Array<PublicAddon>, arg6: string, arg7: boolean, arg8: bigint): Promise<PublicService> {
        if (this.processError) {
            try {
                const result = await this.actor.publicCreateService(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicCreateService(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async publicDeleteLead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publicDeleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicDeleteLead(arg0);
            return result;
        }
    }
    async publicDeleteService(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publicDeleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicDeleteService(arg0);
            return result;
        }
    }
    async publicGetAllLeads(): Promise<Array<PublicLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.publicGetAllLeads();
                return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicGetAllLeads();
            return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async publicGetAllServices(): Promise<Array<PublicService>> {
        if (this.processError) {
            try {
                const result = await this.actor.publicGetAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicGetAllServices();
            return result;
        }
    }
    async publicImportLeads(arg0: Array<{
        status: PublicLeadStatus;
        name: string;
        email: string;
        notes: string;
        phone: string;
    }>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.publicImportLeads(to_candid_vec_n74(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicImportLeads(to_candid_vec_n74(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async publicSeedServices(arg0: Array<PublicService>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.publicSeedServices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicSeedServices(arg0);
            return result;
        }
    }
    async publicSetServiceVisibility(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publicSetServiceVisibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicSetServiceVisibility(arg0, arg1);
            return result;
        }
    }
    async publicUpdateLead(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: PublicLeadStatus, arg5: string): Promise<PublicLead> {
        if (this.processError) {
            try {
                const result = await this.actor.publicUpdateLead(arg0, arg1, arg2, arg3, to_candid_PublicLeadStatus_n67(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_PublicLead_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicUpdateLead(arg0, arg1, arg2, arg3, to_candid_PublicLeadStatus_n67(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_PublicLead_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async publicUpdateService(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<PublicPackage>, arg5: Array<PublicAddon>, arg6: string, arg7: boolean, arg8: bigint): Promise<PublicService> {
        if (this.processError) {
            try {
                const result = await this.actor.publicUpdateService(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicUpdateService(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async receiveExternalWebhook(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.receiveExternalWebhook(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.receiveExternalWebhook(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setServiceVisibility(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setServiceVisibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setServiceVisibility(arg0, arg1);
            return result;
        }
    }
    async updateAdCampaign(arg0: bigint, arg1: string, arg2: AdPlatform, arg3: number, arg4: number, arg5: bigint, arg6: bigint, arg7: bigint): Promise<AdCampaign> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdCampaign(arg0, arg1, to_candid_AdPlatform_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
                return from_candid_AdCampaign_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdCampaign(arg0, arg1, to_candid_AdPlatform_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
            return from_candid_AdCampaign_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEmailCampaign(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Variant_active_sent_draft): Promise<EmailCampaign> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmailCampaign(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg5));
                return from_candid_EmailCampaign_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmailCampaign(arg0, arg1, arg2, arg3, arg4, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg5));
            return from_candid_EmailCampaign_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLandingPage(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: LandingPageStatus): Promise<LandingPage> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLandingPage(arg0, arg1, arg2, arg3, arg4, to_candid_LandingPageStatus_n20(this._uploadFile, this._downloadFile, arg5));
                return from_candid_LandingPage_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLandingPage(arg0, arg1, arg2, arg3, arg4, to_candid_LandingPageStatus_n20(this._uploadFile, this._downloadFile, arg5));
            return from_candid_LandingPage_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLead(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: LeadStatus, arg5: string): Promise<Lead> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, to_candid_LeadStatus_n26(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Lead_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, to_candid_LeadStatus_n26(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Lead_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMetrics(arg0: bigint, arg1: SocialMediaPlatform, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: string): Promise<SocialMediaMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMetrics(arg0, to_candid_SocialMediaPlatform_n32(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return from_candid_SocialMediaMetrics_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMetrics(arg0, to_candid_SocialMediaPlatform_n32(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return from_candid_SocialMediaMetrics_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePost(arg0: bigint, arg1: string, arg2: string, arg3: SocialMediaPlatform, arg4: PostStatus, arg5: bigint | null, arg6: Array<string>, arg7: string): Promise<SocialMediaPost> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(arg0, arg1, arg2, to_candid_SocialMediaPlatform_n32(this._uploadFile, this._downloadFile, arg3), to_candid_PostStatus_n38(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_SocialMediaPost_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(arg0, arg1, arg2, to_candid_SocialMediaPlatform_n32(this._uploadFile, this._downloadFile, arg3), to_candid_PostStatus_n38(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_SocialMediaPost_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSEOEntry(arg0: bigint, arg1: string, arg2: Array<string>, arg3: string, arg4: string): Promise<SEOEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSEOEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSEOEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_AdCampaign_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdCampaign): AdCampaign {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_AdPlatform_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdPlatform): AdPlatform {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_EmailCampaign_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailCampaign): EmailCampaign {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ExportPayload_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportPayload): ExportPayload {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_LandingPageStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LandingPageStatus): LandingPageStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_LandingPage_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LandingPage): LandingPage {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PostStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_PublicLeadStatus_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicLeadStatus): PublicLeadStatus {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_PublicLead_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicLead): PublicLead {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_SocialMediaMetrics_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialMediaMetrics): SocialMediaMetrics {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SocialMediaPlatform_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialMediaPlatform): SocialMediaPlatform {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_SocialMediaPost_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialMediaPost): SocialMediaPost {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdCampaign]): AdCampaign | null {
    return value.length === 0 ? null : from_candid_AdCampaign_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmailCampaign]): EmailCampaign | null {
    return value.length === 0 ? null : from_candid_EmailCampaign_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LandingPage]): LandingPage | null {
    return value.length === 0 ? null : from_candid_LandingPage_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : from_candid_Lead_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SocialMediaMetrics]): SocialMediaMetrics | null {
    return value.length === 0 ? null : from_candid_SocialMediaMetrics_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SocialMediaPost]): SocialMediaPost | null {
    return value.length === 0 ? null : from_candid_SocialMediaPost_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SEOEntry]): SEOEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    clicks: bigint;
    createdAt: bigint;
    impressions: bigint;
    platform: _AdPlatform;
    spend: number;
    updatedAt: bigint;
    conversions: bigint;
    budget: number;
    campaignName: string;
}): {
    id: bigint;
    clicks: bigint;
    createdAt: bigint;
    impressions: bigint;
    platform: AdPlatform;
    spend: number;
    updatedAt: bigint;
    conversions: bigint;
    budget: number;
    campaignName: string;
} {
    return {
        id: value.id,
        clicks: value.clicks,
        createdAt: value.createdAt,
        impressions: value.impressions,
        platform: from_candid_AdPlatform_n14(_uploadFile, _downloadFile, value.platform),
        spend: value.spend,
        updatedAt: value.updatedAt,
        conversions: value.conversions,
        budget: value.budget,
        campaignName: value.campaignName
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        active: null;
    } | {
        sent: null;
    } | {
        draft: null;
    };
    bodyContent: string;
    subjectLine: string;
    createdAt: bigint;
    targetAudience: string;
    updatedAt: bigint;
    campaignName: string;
}): {
    id: bigint;
    status: Variant_active_sent_draft;
    bodyContent: string;
    subjectLine: string;
    createdAt: bigint;
    targetAudience: string;
    updatedAt: bigint;
    campaignName: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n19(_uploadFile, _downloadFile, value.status),
        bodyContent: value.bodyContent,
        subjectLine: value.subjectLine,
        createdAt: value.createdAt,
        targetAudience: value.targetAudience,
        updatedAt: value.updatedAt,
        campaignName: value.campaignName
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    status: _LandingPageStatus;
    name: string;
    createdAt: bigint;
    associatedCampaign: string;
    updatedAt: bigint;
    conversionGoal: string;
}): {
    id: bigint;
    url: string;
    status: LandingPageStatus;
    name: string;
    createdAt: bigint;
    associatedCampaign: string;
    updatedAt: bigint;
    conversionGoal: string;
} {
    return {
        id: value.id,
        url: value.url,
        status: from_candid_LandingPageStatus_n24(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        associatedCampaign: value.associatedCampaign,
        updatedAt: value.updatedAt,
        conversionGoal: value.conversionGoal
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LeadStatus;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
}): {
    id: bigint;
    status: LeadStatus;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n30(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    clicks: bigint;
    engagements: bigint;
    date: bigint;
    createdAt: bigint;
    impressions: bigint;
    platform: _SocialMediaPlatform;
    notes: string;
    postsPublished: bigint;
    followers: bigint;
    reach: bigint;
}): {
    id: bigint;
    clicks: bigint;
    engagements: bigint;
    date: bigint;
    createdAt: bigint;
    impressions: bigint;
    platform: SocialMediaPlatform;
    notes: string;
    postsPublished: bigint;
    followers: bigint;
    reach: bigint;
} {
    return {
        id: value.id,
        clicks: value.clicks,
        engagements: value.engagements,
        date: value.date,
        createdAt: value.createdAt,
        impressions: value.impressions,
        platform: from_candid_SocialMediaPlatform_n36(_uploadFile, _downloadFile, value.platform),
        notes: value.notes,
        postsPublished: value.postsPublished,
        followers: value.followers,
        reach: value.reach
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PostStatus;
    title: string;
    scheduledDate: [] | [bigint];
    createdAt: bigint;
    tags: Array<string>;
    platform: _SocialMediaPlatform;
    updatedAt: bigint;
    notes: string;
    caption: string;
}): {
    id: bigint;
    status: PostStatus;
    title: string;
    scheduledDate?: bigint;
    createdAt: bigint;
    tags: Array<string>;
    platform: SocialMediaPlatform;
    updatedAt: bigint;
    notes: string;
    caption: string;
} {
    return {
        id: value.id,
        status: from_candid_PostStatus_n43(_uploadFile, _downloadFile, value.status),
        title: value.title,
        scheduledDate: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.scheduledDate)),
        createdAt: value.createdAt,
        tags: value.tags,
        platform: from_candid_SocialMediaPlatform_n36(_uploadFile, _downloadFile, value.platform),
        updatedAt: value.updatedAt,
        notes: value.notes,
        caption: value.caption
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metrics: Array<_SocialMediaMetrics>;
    leads: Array<_Lead>;
    posts: Array<_SocialMediaPost>;
    webhookLogs: Array<_WebhookLog>;
}): {
    metrics: Array<SocialMediaMetrics>;
    leads: Array<Lead>;
    posts: Array<SocialMediaPost>;
    webhookLogs: Array<WebhookLog>;
} {
    return {
        metrics: from_candid_vec_n48(_uploadFile, _downloadFile, value.metrics),
        leads: from_candid_vec_n49(_uploadFile, _downloadFile, value.leads),
        posts: from_candid_vec_n50(_uploadFile, _downloadFile, value.posts),
        webhookLogs: value.webhookLogs
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PublicLeadStatus;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
}): {
    id: bigint;
    status: PublicLeadStatus;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_PublicLeadStatus_n71(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedin: null;
} | {
    meta: null;
} | {
    googleAds: null;
} | {
    youtube: null;
}): AdPlatform {
    return "linkedin" in value ? AdPlatform.linkedin : "meta" in value ? AdPlatform.meta : "googleAds" in value ? AdPlatform.googleAds : "youtube" in value ? AdPlatform.youtube : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    sent: null;
} | {
    draft: null;
}): Variant_active_sent_draft {
    return "active" in value ? Variant_active_sent_draft.active : "sent" in value ? Variant_active_sent_draft.sent : "draft" in value ? Variant_active_sent_draft.draft : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    draft: null;
} | {
    paused: null;
}): LandingPageStatus {
    return "active" in value ? LandingPageStatus.active : "draft" in value ? LandingPageStatus.draft : "paused" in value ? LandingPageStatus.paused : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    won: null;
} | {
    lost: null;
} | {
    in_progress: null;
} | {
    open: null;
}): LeadStatus {
    return "won" in value ? LeadStatus.won : "lost" in value ? LeadStatus.lost : "in_progress" in value ? LeadStatus.in_progress : "open" in value ? LeadStatus.open : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedin: null;
} | {
    tiktok: null;
} | {
    twitter: null;
} | {
    other: null;
} | {
    instagram: null;
} | {
    facebook: null;
} | {
    youtube: null;
}): SocialMediaPlatform {
    return "linkedin" in value ? SocialMediaPlatform.linkedin : "tiktok" in value ? SocialMediaPlatform.tiktok : "twitter" in value ? SocialMediaPlatform.twitter : "other" in value ? SocialMediaPlatform.other : "instagram" in value ? SocialMediaPlatform.instagram : "facebook" in value ? SocialMediaPlatform.facebook : "youtube" in value ? SocialMediaPlatform.youtube : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    idea: null;
} | {
    published: null;
} | {
    draft: null;
}): PostStatus {
    return "scheduled" in value ? PostStatus.scheduled : "cancelled" in value ? PostStatus.cancelled : "idea" in value ? PostStatus.idea : "published" in value ? PostStatus.published : "draft" in value ? PostStatus.draft : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    closed_won: null;
} | {
    contacted: null;
} | {
    proposal_sent: null;
} | {
    qualified: null;
}): PublicLeadStatus {
    return "new" in value ? PublicLeadStatus.new : "closed_won" in value ? PublicLeadStatus.closed_won : "contacted" in value ? PublicLeadStatus.contacted : "proposal_sent" in value ? PublicLeadStatus.proposal_sent : "qualified" in value ? PublicLeadStatus.qualified : value;
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SocialMediaMetrics>): Array<SocialMediaMetrics> {
    return value.map((x)=>from_candid_SocialMediaMetrics_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SocialMediaPost>): Array<SocialMediaPost> {
    return value.map((x)=>from_candid_SocialMediaPost_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdCampaign>): Array<AdCampaign> {
    return value.map((x)=>from_candid_AdCampaign_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmailCampaign>): Array<EmailCampaign> {
    return value.map((x)=>from_candid_EmailCampaign_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LandingPage>): Array<LandingPage> {
    return value.map((x)=>from_candid_LandingPage_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicLead>): Array<PublicLead> {
    return value.map((x)=>from_candid_PublicLead_n69(_uploadFile, _downloadFile, x));
}
function to_candid_AdPlatform_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdPlatform): _AdPlatform {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_LandingPageStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LandingPageStatus): _LandingPageStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_Lead_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lead): _Lead {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_PostStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): _PostStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_PublicLeadStatus_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicLeadStatus): _PublicLeadStatus {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid_SocialMediaPlatform_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialMediaPlatform): _SocialMediaPlatform {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: LeadStatus;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
}): {
    id: bigint;
    status: _LeadStatus;
    name: string;
    createdAt: bigint;
    email: string;
    updatedAt: bigint;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        status: to_candid_LeadStatus_n26(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        updatedAt: value.updatedAt,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PublicLeadStatus;
    name: string;
    email: string;
    notes: string;
    phone: string;
}): {
    status: _PublicLeadStatus;
    name: string;
    email: string;
    notes: string;
    phone: string;
} {
    return {
        status: to_candid_PublicLeadStatus_n67(_uploadFile, _downloadFile, value.status),
        name: value.name,
        email: value.email,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdPlatform): {
    linkedin: null;
} | {
    meta: null;
} | {
    googleAds: null;
} | {
    youtube: null;
} {
    return value == AdPlatform.linkedin ? {
        linkedin: null
    } : value == AdPlatform.meta ? {
        meta: null
    } : value == AdPlatform.googleAds ? {
        googleAds: null
    } : value == AdPlatform.youtube ? {
        youtube: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_sent_draft): {
    active: null;
} | {
    sent: null;
} | {
    draft: null;
} {
    return value == Variant_active_sent_draft.active ? {
        active: null
    } : value == Variant_active_sent_draft.sent ? {
        sent: null
    } : value == Variant_active_sent_draft.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LandingPageStatus): {
    active: null;
} | {
    draft: null;
} | {
    paused: null;
} {
    return value == LandingPageStatus.active ? {
        active: null
    } : value == LandingPageStatus.draft ? {
        draft: null
    } : value == LandingPageStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    won: null;
} | {
    lost: null;
} | {
    in_progress: null;
} | {
    open: null;
} {
    return value == LeadStatus.won ? {
        won: null
    } : value == LeadStatus.lost ? {
        lost: null
    } : value == LeadStatus.in_progress ? {
        in_progress: null
    } : value == LeadStatus.open ? {
        open: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialMediaPlatform): {
    linkedin: null;
} | {
    tiktok: null;
} | {
    twitter: null;
} | {
    other: null;
} | {
    instagram: null;
} | {
    facebook: null;
} | {
    youtube: null;
} {
    return value == SocialMediaPlatform.linkedin ? {
        linkedin: null
    } : value == SocialMediaPlatform.tiktok ? {
        tiktok: null
    } : value == SocialMediaPlatform.twitter ? {
        twitter: null
    } : value == SocialMediaPlatform.other ? {
        other: null
    } : value == SocialMediaPlatform.instagram ? {
        instagram: null
    } : value == SocialMediaPlatform.facebook ? {
        facebook: null
    } : value == SocialMediaPlatform.youtube ? {
        youtube: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    idea: null;
} | {
    published: null;
} | {
    draft: null;
} {
    return value == PostStatus.scheduled ? {
        scheduled: null
    } : value == PostStatus.cancelled ? {
        cancelled: null
    } : value == PostStatus.idea ? {
        idea: null
    } : value == PostStatus.published ? {
        published: null
    } : value == PostStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicLeadStatus): {
    new: null;
} | {
    closed_won: null;
} | {
    contacted: null;
} | {
    proposal_sent: null;
} | {
    qualified: null;
} {
    return value == PublicLeadStatus.new ? {
        new_: null
    } : value == PublicLeadStatus.closed_won ? {
        closed_won: null
    } : value == PublicLeadStatus.contacted ? {
        contacted: null
    } : value == PublicLeadStatus.proposal_sent ? {
        proposal_sent: null
    } : value == PublicLeadStatus.qualified ? {
        qualified: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Lead>): Array<_Lead> {
    return value.map((x)=>to_candid_Lead_n65(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    status: PublicLeadStatus;
    name: string;
    email: string;
    notes: string;
    phone: string;
}>): Array<{
    status: _PublicLeadStatus;
    name: string;
    email: string;
    notes: string;
    phone: string;
}> {
    return value.map((x)=>to_candid_record_n75(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
